export const FETCH_REPORTS = 'FETCH_REPORTS';
export const FETCH_REPORTS_ERROR = 'FETCH_REPORTS_ERROR';
export const RESOLVE_TICKET = 'RESOLVE_TICKET';
export const RESOLVE_TICKET_ERROR = 'RESOLVE_TICKET_ERROR';
